// ════════════════════════════════════════
// STOCK DATABASE — 45 stocks
// ════════════════════════════════════════
const DB=[
  {s:'NVDA',n:'Nvidia Corp',sec:'Technology',cap:'Large',div:0.03,risk:7,mgmt:9.8,signal:'STRONG HOLD',signalType:'strong',
   reason:'AI infrastructure demand accelerating. Blackwell supply constrained — demand exceeds capacity for 3rd consecutive quarter. CUDA moat deepening as enterprise developers lock in. Insider activity clean. No reason to touch this position.',
   confidence:96,
   thesis:'Nvidia owns the infrastructure layer of the AI revolution. The CUDA ecosystem creates switching costs so deep that technically superior competitors cannot displace it. Every major AI model is trained on Nvidia hardware. Data center GPU demand is structurally compounding.',
   management:"Jensen Huang co-founded Nvidia in 1993. He missed mobile but pivoted the entire company to accelerated computing with prescient timing. Conservative compensation relative to company size. Zero history of empire-building. Earnings call language analysis: 9.8/10 — technical specificity, falsifiable predictions, almost no hedging when discussing demand.",
   whyfit:'AI infrastructure sector match. CEO quality 9.8/10. High return potential aligns with moderate-aggressive risk profiles.',
   risks:'Taiwan geopolitical risk (TSMC dependency). AMD gaining inference share. US export restrictions to China impacting ~25% of revenue.',
   metrics:[{v:'87%',l:'Gross Margin'},{v:'9.8/10',l:'CEO Score'},{v:'+3.4%',l:'Today'}]},

  {s:'MSFT',n:'Microsoft',sec:'Technology',cap:'Large',div:0.7,risk:5,mgmt:9.5,signal:'STRONG HOLD',signalType:'strong',
   reason:"Azure AI revenue accelerated to 33% growth this quarter — above consensus. Copilot enterprise penetration is accelerating. 22-year dividend streak intact with room to grow. Nadella's execution remains world-class. No action needed.",
   confidence:94,
   thesis:'Microsoft owns the enterprise software stack and monetizes AI faster than any other large-cap. Copilot embedded across Word, Excel, Teams, Azure. Enterprise contracts create multi-year lock-in. Azure gaining cloud market share 8 consecutive quarters.',
   management:"Satya Nadella shifted Microsoft from Windows-centric to cloud-first when the stock had been flat for 14 years. LinkedIn ($26B), GitHub ($7.5B), Activision ($68B) — every acquisition created value. Earnings scoring: 9.5/10. Uncommon clarity about competitive position.",
   whyfit:'Dividend Aristocrat (22yr streak) + cloud growth. Quality anchor for moderate risk profiles.',
   risks:'EU regulatory scrutiny on AI/cloud bundling. OpenAI dependency concentration risk.',
   metrics:[{v:'22yr',l:'Div Streak'},{v:'9.5/10',l:'CEO Score'},{v:'0.7%',l:'Yield'}]},

  {s:'AMZN',n:'Amazon',sec:'Technology',cap:'Large',div:0,risk:6,mgmt:8.9,signal:'HOLD',signalType:'hold',
   reason:"AWS margins expanding — Q1 operating income above estimates. Advertising revenue growing 22%. No near-term catalysts to add but thesis intact. Hold and let compounding work.",
   confidence:82,
   thesis:"Amazon is two world-class businesses priced as one. AWS is the most profitable cloud platform on earth at 37% operating margins. Advertising is growing 20%+ annually and is the most underappreciated business Amazon owns.",
   management:"Andy Jassy maintained Bezos's long-term orientation while adding cost discipline. The 2022-2023 restructuring (27,000 jobs) demonstrated willingness to make hard decisions. AWS acceleration under his leadership validates strategic capability. Earnings: 8.9/10.",
   whyfit:'E-commerce + cloud + advertising diversification. AWS margin expansion underappreciated by market.',
   risks:'AWS competitive pressure from Azure. FTC antitrust scrutiny. International margin expansion slower than expected.',
   metrics:[{v:'37%',l:'AWS Margin'},{v:'8.9/10',l:'CEO Score'},{v:'+21%',l:'Rev Growth'}]},

  {s:'META',n:'Meta Platforms',sec:'Technology',cap:'Large',div:0.4,risk:6,mgmt:8.2,signal:'HOLD',signalType:'hold',
   reason:'43% operating margins and AI ad efficiency improving quarter over quarter. Llama adoption metrics strong. EU regulatory risk elevated — monitoring GDPR proceedings. Maintain position, no change needed this week.',
   confidence:80,
   thesis:"Meta owns the world's social graph — 3.3 billion daily users. 43% operating margins. AI increasing ad relevance dramatically. Llama becoming the open-source AI standard commoditizes competitors while Meta retains data advantages.",
   management:"Zuckerberg's 2022 Year of Efficiency proved he can cut ruthlessly when needed. Open-sourcing Llama is strategic genius given adoption metrics. $50B buyback authorized. Earnings: 8.2/10.",
   whyfit:'High-quality growth at reasonable valuation. 43% margins fund massive AI investment. Dividend + buyback provides returns floor.',
   risks:'EU regulatory risk with large fines possible. Metaverse investments ($40B+) unproven. Teen usage declining in Western markets.',
   metrics:[{v:'3.3B',l:'Daily Users'},{v:'8.2/10',l:'CEO Score'},{v:'43%',l:'Op Margin'}]},

  {s:'PLTR',n:'Palantir',sec:'AI / Data',cap:'Large',div:0,risk:8,mgmt:9.1,signal:'STRONG HOLD',signalType:'strong',
   reason:"Karp's $2.1M open-market purchase on Feb 28 is one of the strongest insider signals in our database this year. Non-10b5-1 CEO purchases historically outperform by 8.2% over 12 months. Commercial AIP growth 41% — accelerating. Adding to position makes sense for aggressive profiles.",
   confidence:91,
   thesis:"Palantir builds the intelligence layer for governments and enterprises. US government business is a 20-year moat — security clearances, embedded workflows, relationships that took decades. AIP commercial winning enterprise deals at 41% growth.",
   management:"Alex Karp is one of the most unconventional CEOs in American business. His $2.1M open-market stock purchase is one of the strongest insider signals in our database. Earnings: 9.1/10. Willingness to take public positions on ethics and geopolitics creates differentiation that attracts exceptional talent.",
   whyfit:'AI + government tech match. CEO open-market buy is exceptional signal. Suitable for aggressive profiles with 10+ year horizon.',
   risks:'High valuation (60x+ revenue) requires sustained 30%+ growth. Government contract concentration.',
   metrics:[{v:'9.1/10',l:'CEO Score'},{v:'$2.1M',l:'Insider Buy'},{v:'+41%',l:'Comm Growth'}]},

  {s:'AVGO',n:'Broadcom Inc',sec:'Technology',cap:'Large',div:1.6,risk:5,mgmt:9.3,signal:'HOLD',signalType:'hold',
   reason:'VMware integration ahead of schedule — cost synergies exceeding targets. Custom AI chip revenue (XPUs) growing rapidly for Google and Meta. 14-year dividend streak with 34% CAGR. No reason to swap. Dividend due next month.',
   confidence:88,
   thesis:"Broadcom: acquire mission-critical products, optimize costs, raise prices on captive customers, return cash. VMware adds $8.5B+ ARR. Custom AI accelerator chips for hyperscalers are a multi-billion new revenue stream.",
   management:"Hock Tan is arguably the best M&A operator in technology history. Every acquisition created value. VMware integration is 6 months ahead of schedule. Most metrics-driven CEO communications in our database. Earnings: 9.3/10.",
   whyfit:'Semiconductor + dividend growth combination. 14-year streak with 34% 5yr CAGR. Highest management score in semiconductor sector.',
   risks:'VMware integration complexity. Apple as concentrated revenue customer. TSMC supply chain dependency.',
   metrics:[{v:'14yr',l:'Div Streak'},{v:'9.3/10',l:'CEO Score'},{v:'+34%',l:'Div CAGR'}]},

  {s:'JNJ',n:'Johnson & Johnson',sec:'Healthcare',cap:'Large',div:3.2,risk:2,mgmt:8.8,signal:'HOLD',signalType:'hold',
   reason:"62nd dividend increase just announced — 4.8% raise. Skyrizi biosimilar headwinds well-understood and priced in. Talc litigation progressing toward resolution. AAA credit, Dividend King. Core defensive hold. No change.",
   confidence:85,
   thesis:"J&J is the gold standard of durable dividend compounding. 62 consecutive years of dividend growth. The Kenvue spin-off creates a cleaner MedTech and Pharma story that should re-rate higher.",
   management:"Joaquin Duato managed ongoing talc litigation effectively. J&J holds one of only two AAA credit ratings among all US companies. Earnings: 8.8/10 — conservative, precise, sets expectations he consistently meets.",
   whyfit:'Dividend King (62yr). AAA credit. Defensive anchor. Yield-on-cost compounds dramatically with DRIP.',
   risks:'Talc litigation ongoing. Biosimilar competition for Stelara reducing revenue. MedTech growth below pure-play peers.',
   metrics:[{v:'62yr',l:'Div Streak'},{v:'3.2%',l:'Yield'},{v:'AAA',l:'Credit'}]},

  {s:'ABBV',n:'AbbVie',sec:'Healthcare',cap:'Large',div:3.8,risk:4,mgmt:8.4,signal:'HOLD',signalType:'hold',
   reason:'Skyrizi and Rinvoq growing 50%+ — Humira cliff derisked. 50+ consecutive dividend increases intact. No near-term thesis change.',
   confidence:83,
   thesis:"AbbVie navigating the Humira patent cliff better than analysts predicted. Skyrizi and Rinvoq on track to generate more revenue than Humira at its peak. Deep pipeline in immunology, oncology, neuroscience.",
   management:"Richard Gonzalez executed through the Humira cliff. Allergan acquisition ($63B) added Botox and pipeline now generating significant revenue. Earnings: 8.4/10.",
   whyfit:'High yield + dividend growth. Biotech/healthcare sector match. Humira transition derisked.',
   risks:'Skyrizi/Rinvoq face eventual patent cliffs. Neuroscience pipeline is high-risk high-reward.',
   metrics:[{v:'3.8%',l:'Yield'},{v:'50yr+',l:'Div Growth'},{v:'8.4/10',l:'CEO Score'}]},

  {s:'LLY',n:'Eli Lilly',sec:'Healthcare',cap:'Large',div:0.7,risk:6,mgmt:9.0,signal:'STRONG HOLD',signalType:'strong',
   reason:'GLP-1 demand continues to exceed supply — manufacturing investment is the right constraint to have. Tirzepatide taking market share from Ozempic in head-to-head trials. Pipeline beyond GLP-1 adds optionality. Revenue guidance raised.',
   confidence:92,
   thesis:"Eli Lilly owns the GLP-1 obesity drug market. Tirzepatide outperforming Ozempic in trials. 1 billion+ people globally qualify for obesity treatment. Revenue growing 30%+ annually.",
   management:"David Ricks went all-in on GLP-1 before the market understood the opportunity — that bet is now worth $500B+ in market cap creation. Manufacturing investment ahead of demand shows conviction. Earnings: 9.0/10.",
   whyfit:'Healthcare sector match. GLP-1 is a generational drug class. Strong management conviction bet.',
   risks:'GLP-1 competition if new entrants succeed. Manufacturing scale-up constraints. High PE (60x+).',
   metrics:[{v:'+30%',l:'Rev Growth'},{v:'9.0/10',l:'CEO Score'},{v:'0.7%',l:'Yield'}]},

  {s:'UNH',n:'UnitedHealth',sec:'Healthcare',cap:'Large',div:1.8,risk:5,mgmt:7.8,signal:'WATCH',signalType:'watch',
   reason:'Political and regulatory pressure on health insurance practices is intensifying following Q4 controversy. Medical cost ratio elevated. Short-term overhang on the stock. Maintaining position but flagging for review — consider trimming if regulatory risk escalates.',
   confidence:62,
   thesis:"UnitedHealth is the largest health insurer in the US with Optum as a rapidly growing second business. Vertical integration of insurance + pharmacy + physician groups creates a powerful ecosystem. Cash flow generation is extraordinary.",
   management:"Following the tragic death of CEO Brian Thompson, company navigating leadership transition. The business model is deeply entrenched despite ongoing public controversy. Earnings: 7.8/10.",
   whyfit:'Healthcare sector match. Consistent cash flow supports dividend growth. Defensive in downturns.',
   risks:'Political and regulatory risk on insurance practices intensifying. Medical cost inflation. Public controversy.',
   metrics:[{v:'1.8%',l:'Yield'},{v:'14yr',l:'Div Growth'},{v:'7.8/10',l:'CEO Score'}],
   swapSuggestion:{sym:'LLY',reason:'If you are concerned about UNH regulatory risk, consider increasing your LLY position — it captures healthcare sector exposure with a cleaner regulatory profile and the GLP-1 secular tailwind.'}},

  {s:'V',n:'Visa Inc',sec:'Financials',cap:'Large',div:0.8,risk:4,mgmt:9.2,signal:'STRONG HOLD',signalType:'strong',
   reason:'Payment volumes growing 9% globally. Cross-border transactions fully recovered post-COVID. New payment flows (B2B, real-time) expanding TAM. One of the cleanest compounders in the market. No action needed.',
   confidence:93,
   thesis:"Visa is the world's largest payment network — a toll road on the global economy. 4.3 billion cards, 130M merchant locations. Revenue grows with global GDP and inflation without requiring capital reinvestment.",
   management:"Ryan McInerney focuses on new payment flows expanding Visa's TAM. The business is so well-run that even mediocre management would compound well. McInerney is considerably above average. Earnings: 9.2/10.",
   whyfit:'Financials sector match. Low risk (4/10) with exceptional quality moat. Dividend aristocrat growing 15%+ annually.',
   risks:'Government regulation on interchange fees. Crypto as long-term disruptor. BNPL taking some share.',
   metrics:[{v:'0.8%',l:'Yield'},{v:'9.2/10',l:'CEO Score'},{v:'65%',l:'Net Margin'}]},

  {s:'MA',n:'Mastercard',sec:'Financials',cap:'Large',div:0.6,risk:4,mgmt:9.1,signal:'HOLD',signalType:'hold',
   reason:'Effectively identical to Visa thesis. Both are excellent. If you only hold one, either works. No action needed.',
   confidence:88,
   thesis:"Mastercard processes $8T+ in annual payments across 210+ countries. Value-added services growing faster than core network revenue at higher margins. Near-duopoly with Visa creates extraordinary pricing power.",
   management:"Michael Miebach accelerating diversification into open banking and real-time payments. Exceptional capital discipline. Earnings: 9.1/10. Extremely consistent and metric-focused.",
   whyfit:'Financials sector match. Payment network duopoly with extraordinary pricing power. Low risk consistent compounder.',
   risks:'Same regulatory and crypto risks as Visa. Real-time payment rails as long-term disintermediator.',
   metrics:[{v:'0.6%',l:'Yield'},{v:'9.1/10',l:'CEO Score'},{v:'44%',l:'Net Margin'}]},

  {s:'VYM',n:'Vanguard High Div ETF',sec:'Technology',cap:'Large',div:2.9,risk:3,mgmt:9.5,signal:'HOLD',signalType:'hold',
   reason:"Broad dividend exposure performing as expected. 2.9% yield with steady growth. No single-stock risk. Rate cut signal is modestly positive for dividend stocks. Hold.",
   confidence:87,
   thesis:"VYM provides instant diversified exposure to 450+ US dividend-paying stocks at 0.06% expense ratio. Systematically screens for dividend sustainability, avoiding yield traps.",
   management:"Vanguard as an institution: investor-owned, consistently lowers expense ratios, votes shares in shareholders' interest. Earnings equivalent: 9.5/10 for stewardship.",
   whyfit:'Core income ETF. Dividend strategy match. Low cost (0.06%) maximizes compounding.',
   risks:'Rising rates compress high-dividend stock valuations. No individual stock upside.',
   metrics:[{v:'2.9%',l:'Yield'},{v:'0.06%',l:'Expense Ratio'},{v:'450+',l:'Holdings'}]},

  {s:'QQQ',n:'Invesco QQQ ETF',sec:'Technology',cap:'Large',div:0.6,risk:6,mgmt:9.0,signal:'HOLD',signalType:'hold',
   reason:'17%+ 20-year CAGR. AI era is directly benefitting the Nasdaq-100. Rate cut signal is bullish. Core tech exposure with no single-stock risk. Hold.',
   confidence:84,
   thesis:"QQQ tracks the top 100 non-financial Nasdaq companies. 17%+ annually over 20 years. In the AI era, Nasdaq-100 companies are the primary beneficiaries of the transformation.",
   management:"Invesco scores 9.0/10 for fund management. One of the most liquid ETFs globally. Underlying companies have some of the highest average management scores in our database.",
   whyfit:'Core technology ETF. Efficient exposure to AI/tech growth without single-stock risk.',
   risks:'Concentrated in top 10 holdings (55%+). Tech downturns hit hard. Higher PE sensitive to rate changes.',
   metrics:[{v:'+17%',l:'20yr CAGR'},{v:'0.20%',l:'Expense Ratio'},{v:'100',l:'Companies'}]},

  {s:'TQQQ',n:'ProShares UltraPro QQQ',sec:'Technology',cap:'Large',div:0,risk:10,mgmt:8.0,signal:'WATCH',signalType:'watch',
   reason:'3x leverage during elevated geopolitical uncertainty warrants monitoring. Volatility decay risk increases in sideways markets. Only appropriate for aggressive profiles with 15+ year horizons who will not sell during drawdowns. Flagging for review.',
   confidence:55,
   thesis:"TQQQ is the 3x leveraged Nasdaq-100 ETF. In sustained bull markets generates extraordinary long-term returns. Daily rebalancing creates volatility decay in sideways markets.",
   management:"ProShares: 8.0/10. The fund does exactly what it says. WARNING: -33% single-day drop = near-total loss. Maximum 5-10% of any portfolio.",
   whyfit:'ONLY for aggressive profiles with 15+ year horizons who will never panic sell.',
   risks:'A -33% single-day decline = near-total loss. Volatility decay. Not suitable for short/medium horizons.',
   metrics:[{v:'3x',l:'Daily Leverage'},{v:'-80%',l:'Max Drawdown'},{v:'0.88%',l:'Expense Ratio'}]},

  {s:'CRWD',n:'CrowdStrike',sec:'Technology',cap:'Large',div:0,risk:7,mgmt:8.4,signal:'HOLD',signalType:'hold',
   reason:'ARR growing 31%, >120% net retention. 2024 outage impact on new logo sales largely resolved. Government contracts expanding. AI-native platform widening moat. Hold.',
   confidence:81,
   thesis:"CrowdStrike is the cybersecurity platform winner. Falcon is AI-native — gets smarter as it processes more threats. Network effect of threat intelligence: larger scale = better protection = more customers.",
   management:"George Kurtz handled the 2024 outage with transparent, rapid response — mature crisis management. Earnings: 8.4/10. Strong technical depth in communications.",
   whyfit:'Technology/cybersecurity match. AI-native platform creates compounding advantages. High switching costs.',
   risks:'2024 outage reputational risk. Microsoft as well-resourced competitor. High valuation requires continued rapid growth.',
   metrics:[{v:'+31%',l:'ARR Growth'},{v:'75%',l:'Gross Margin'},{v:'8.4/10',l:'CEO Score'}]},

  {s:'PANW',n:'Palo Alto Networks',sec:'Technology',cap:'Large',div:0,risk:7,mgmt:8.6,signal:'HOLD',signalType:'hold',
   reason:'Platform consolidation strategy working — customers adding more modules. ARR growing 20%, renewal rates excellent. Government security spend increasing. Hold.',
   confidence:82,
   thesis:"Palo Alto is the largest pure-play cybersecurity company. Platform strategy consolidates point security products onto one unified platform, creating enormous switching costs and upsell opportunity.",
   management:"Nikesh Arora pivoted Palo Alto to a platform strategy in 2018 — transformation that created massive value. Thinks like a tech executive, not a security vendor. Earnings: 8.6/10.",
   whyfit:'Technology/cybersecurity match. Platform consolidation trend plays into their strength.',
   risks:'CrowdStrike and Microsoft as well-resourced competitors. Platformization requires sustained execution.',
   metrics:[{v:'+20%',l:'ARR Growth'},{v:'8.6/10',l:'CEO Score'},{v:'72%',l:'Gross Margin'}]},

  {s:'NOW',n:'ServiceNow',sec:'Technology',cap:'Large',div:0,risk:6,mgmt:9.2,signal:'STRONG HOLD',signalType:'strong',
   reason:'Most embedded enterprise software platform. AI copilots expanding revenue per customer significantly. Net retention >120%. McDermott execution flawless. Adding to position makes sense for moderate-aggressive profiles.',
   confidence:90,
   thesis:"ServiceNow is the operating system for enterprise workflows. Every large company uses it. Replacing it would take years and hundreds of millions. AI copilots layered on top are expanding revenue per customer dramatically.",
   management:"Bill McDermott is one of the best enterprise software CEOs alive. Transformed SAP, executing the same playbook at ServiceNow. Focus on customer success over deal size. Earnings: 9.2/10.",
   whyfit:'Technology/cloud SaaS match. Best-in-class switching costs. AI expansion creating new revenue streams.',
   risks:'High valuation (50x+) sensitive to growth deceleration. Microsoft Copilot overlap. Macro recession slows enterprise IT spending.',
   metrics:[{v:'+21%',l:'Rev Growth'},{v:'9.2/10',l:'CEO Score'},{v:'82%',l:'Gross Margin'}]},

  {s:'ASML',n:'ASML Holding',sec:'Technology',cap:'Large',div:1.1,risk:6,mgmt:9.0,signal:'HOLD',signalType:'hold',
   reason:'EUV machines booked years in advance. No competitor within a decade of catching up. Taiwan geopolitical risk is the main watch item — monitoring closely. Export restriction risk partially priced in. Hold.',
   confidence:85,
   thesis:"ASML is the only company that makes EUV lithography machines required to manufacture advanced semiconductors. Intel, TSMC, Samsung must buy from ASML. No alternative exists.",
   management:"ASML is institutionally excellent — moat so deep management quality matters less. Leadership consistently maintains the R&D investment sustaining technological lead. Earnings: 9.0/10.",
   whyfit:'Technology/semiconductor match. Most defensible monopoly in the semiconductor supply chain.',
   risks:'Dutch/US export restrictions limiting China sales. Geopolitical risk disrupting TSMC. Customer concentration.',
   metrics:[{v:'1.1%',l:'Yield'},{v:'9.0/10',l:'CEO Score'},{v:'Monopoly',l:'EUV Market'}]},

  {s:'AMD',n:'Advanced Micro Devices',sec:'Technology',cap:'Large',div:0,risk:7,mgmt:9.3,signal:'HOLD',signalType:'hold',
   reason:'MI300X gaining real adoption in inference workloads. Data center growing 94% YoY. Lisa Su execution remains exceptional. Valuation is reasonable relative to growth rate. Hold.',
   confidence:82,
   thesis:"AMD is the only credible competitor to NVIDIA in AI chips. MI300X gaining adoption in AI inference. Data center grew 94% in 2024. Lisa Su executing the most impressive comeback in semiconductor history.",
   management:"Lisa Su inherited near-bankrupt AMD in 2014 and transformed it through relentless execution and product quality. Investing in TSMC advanced nodes when cash was tight took courage and paid off. Earnings: 9.3/10.",
   whyfit:'Technology/semiconductor match. Credible NVIDIA alternative with meaningful AI exposure. CEO quality 9.3 is exceptional.',
   risks:'NVIDIA CUDA ecosystem creates enormous switching costs AMD must overcome. PC market cyclicality.',
   metrics:[{v:'+94%',l:'DC Rev Growth'},{v:'9.3/10',l:'CEO Score'},{v:'53%',l:'Gross Margin'}]},

  {s:'O',n:'Realty Income',sec:'Real Estate',cap:'Large',div:5.4,risk:3,mgmt:8.6,signal:'HOLD',signalType:'hold',
   reason:'Monthly dividend paid for 30+ years. 125 consecutive quarterly raises. Rate cut signal is bullish for REITs. Net lease structure means 15,000+ tenants pay all operating costs. Core income hold.',
   confidence:86,
   thesis:"Realty Income pays monthly dividends for 30+ years, 125 consecutive quarterly raises. Net lease REIT: tenants pay property taxes, insurance, maintenance. 15,000+ properties leased to investment-grade tenants.",
   management:"Sumit Roy grew Realty Income from $15B to $50B+ enterprise. Capital allocation consistently accretive. Earnings: 8.6/10. Clear and metrics-driven quarterly communications.",
   whyfit:'Real Estate/REIT match. 5.4% monthly yield. 30-year dividend history. Perfect for income-focused investors.',
   risks:'Rising rates compress REIT valuations. Retail tenant bankruptcies. Slow capital appreciation vs growth stocks.',
   metrics:[{v:'5.4%',l:'Monthly Yield'},{v:'30yr+',l:'Div Streak'},{v:'8.6/10',l:'CEO Score'}]},

  {s:'NEE',n:'NextEra Energy',sec:'Utilities',cap:'Large',div:3.1,risk:3,mgmt:8.2,signal:'HOLD',signalType:'hold',
   reason:"World's largest wind/solar producer + regulated Florida utility. AI data center electricity demand is a structural tailwind nobody is fully pricing in yet. Rate cut signal is modestly positive. Hold.",
   confidence:83,
   thesis:"NextEra is both the largest US electric utility and world's largest wind/solar producer. AI data center electricity demand is a structural tailwind — data centers use 10-15x more electricity per square foot than typical commercial real estate.",
   management:"John Ketchum maintained the long-term capital allocation discipline that made NextEra the most valuable utility in the world. Compounded earnings 8-10% annually for 20+ years. Earnings: 8.2/10.",
   whyfit:'Utilities/clean energy match. 3.1% yield with reliable growth. Low risk. Perfect for conservative profiles.',
   risks:'Rising rates compress utility valuations. Renewable project delays. Florida rate regulation changes.',
   metrics:[{v:'3.1%',l:'Yield'},{v:'8.2/10',l:'CEO Score'},{v:'27yr',l:'Div Growth'}]},

  {s:'COST',n:'Costco Wholesale',sec:'Consumer',cap:'Large',div:0.7,risk:3,mgmt:9.4,signal:'STRONG HOLD',signalType:'strong',
   reason:'93% membership renewal rate unchanged. Special dividend expected Q3 2026. Inflation environment is ideal for Costco — members perceive value as exceptional. New CEO continuing Sinegal playbook. No action needed.',
   confidence:92,
   thesis:"Costco is the most operationally excellent retailer. Membership model means it earns a fee just for customers to shop — 93% renew. The treasure hunt experience and brutal price discipline create extraordinary loyalty.",
   management:"Ron Vachris continuing the culture Jim Sinegal built over 40 years. Every CEO has come from within — definition of institutional excellence. Never had a major scandal. Earnings: 9.4/10. Always delivers slightly above guidance.",
   whyfit:'Consumer/consumer staples match. 93% membership renewal rate is an unsung moat. Low risk with exceptional management.',
   risks:'Premium valuation (50x+ PE) for a retailer. E-commerce competitive pressure. International expansion execution.',
   metrics:[{v:'0.7%',l:'Yield'},{v:'9.4/10',l:'CEO Score'},{v:'93%',l:'Member Renewal'}]},

  {s:'XOM',n:'ExxonMobil',sec:'Energy',cap:'Large',div:3.6,risk:4,mgmt:8.4,signal:'HOLD',signalType:'hold',
   reason:'Pioneer acquisition doubling Permian Basin acreage is underappreciated. Oil price stable at $72/barrel. Dividend growing for 41 consecutive years. Non-tech diversification value in current macro. Hold.',
   confidence:79,
   thesis:"ExxonMobil is the most financially disciplined major oil company — positive free cash flow even at $40/barrel oil. Pioneer acquisition doubled its best Permian Basin acreage.",
   management:"Darren Woods presided over dramatic operational efficiency improvement and the transformative Pioneer acquisition. Capital discipline returning cash rather than expanding production recklessly. Earnings: 8.4/10.",
   whyfit:'Energy sector match. 3.6% yield with 41 consecutive years of growth. Portfolio diversification.',
   risks:'Long-term oil demand decline as EVs penetrate. Carbon regulation acceleration.',
   metrics:[{v:'3.6%',l:'Yield'},{v:'41yr',l:'Div Growth'},{v:'8.4/10',l:'CEO Score'}]},

  {s:'RTX',n:'RTX Corporation',sec:'Industrials',cap:'Large',div:2.1,risk:4,mgmt:7.8,signal:'HOLD',signalType:'hold',
   reason:'Defense budgets structurally increasing as NATO allies hit 2% GDP targets. GTF engine issues still being resolved but manageable. Geopolitical tension is sad but structurally beneficial for defense contractors. Hold.',
   confidence:77,
   thesis:"RTX manufactures Patriot missile systems, F135 jet engines, advanced radar systems. Defense budgets structurally increasing as global tensions remain elevated. Aerospace recovery adds commercial tailwind.",
   management:"Christopher Calio managing through GTF engine issues with appropriate transparency. Defense business is a government-contracted annuity. Earnings: 7.8/10.",
   whyfit:'Industrials/defense match. Geopolitical tension increases defense demand. Dividend payer for non-tech diversification.',
   risks:'GTF engine manufacturing problems ongoing. Defense budget cuts possible. Government contract profitability is regulated.',
   metrics:[{v:'2.1%',l:'Yield'},{v:'7.8/10',l:'CEO Score'},{v:'$20B+',l:'Backlog'}]},

  {s:'PG',n:'Procter & Gamble',sec:'Consumer',cap:'Large',div:2.4,risk:2,mgmt:8.6,signal:'HOLD',signalType:'hold',
   reason:'67-year dividend streak. Pricing power in inflationary environments. Premiumization strategy maintaining margins. Maximum stability consumer staple. Hold.',
   confidence:88,
   thesis:"P&G owns the most durable consumer brand portfolio in the world — Tide, Pampers, Gillette, Oral-B. Pricing power allows passing inflation to consumers. 67 consecutive years of dividend increases.",
   management:"Jon Moeller shifted portfolio upmarket — premiumization creating stronger margins and brand loyalty. Earnings: 8.6/10. Extremely consistent quarterly communications.",
   whyfit:'Consumer/staples match. 67-year dividend streak. Maximum stability. Ideal defensive holding.',
   risks:'Private label competition in downturns. Raw material cost inflation. International currency headwinds.',
   metrics:[{v:'2.4%',l:'Yield'},{v:'67yr',l:'Div Streak'},{v:'8.6/10',l:'CEO Score'}]},

  {s:'KO',n:'Coca-Cola',sec:'Consumer',cap:'Large',div:3.2,risk:2,mgmt:8.5,signal:'HOLD',signalType:'hold',
   reason:'62 consecutive dividend increases. 2,000+ brands in 200+ countries. $10B+ free cash flow annually. Warren Buffett holds it for a reason. Maximum durability. Hold.',
   confidence:89,
   thesis:"Coca-Cola is one of the most durable businesses ever created. 2,000+ brands in 200+ countries. Distribution network built over 100 years is nearly impossible to replicate.",
   management:"James Quincey expanded beyond carbonated beverages into coffee, sports drinks, water. Consistent margin management through commodity cycles. Earnings: 8.5/10. Buffett's largest holding.",
   whyfit:'Consumer/staples match. 3.2% yield with 62-year growth streak. Dividend King. Maximum stability.',
   risks:'Sugar regulation and consumer health trends. Emerging market currency exposure. Plastic regulation.',
   metrics:[{v:'3.2%',l:'Yield'},{v:'62yr',l:'Div Streak'},{v:'8.5/10',l:'CEO Score'}]},

  {s:'ENPH',n:'Enphase Energy',sec:'Energy',cap:'Mid',div:0,risk:8,mgmt:7.8,signal:'WATCH',signalType:'watch',
   reason:'Residential solar demand still recovering from 2023 inventory correction. European demand weaker than expected. Microinverter moat intact but near-term growth below expectations. Watching for recovery confirmation before adding.',
   confidence:58,
   swapSuggestion:{sym:'NEE',reason:'If clean energy conviction remains but you want less volatility, consider NextEra Energy — it captures the clean energy buildout with regulated utility stability and a 3.1% dividend.'},
   thesis:"Enphase is the microinverter technology leader in residential solar. Unlike string inverters, microinverters optimize each panel independently — generating 5-25% more energy. Battery storage is a growing second revenue stream.",
   management:"Badri Kothandaraman led Enphase through its 2018 turnaround and explosive growth. Honest about near-term headwinds. Earnings: 7.8/10.",
   whyfit:'Energy/clean energy match. Microinverter moat is technically defensible. Battery storage adds TAM.',
   risks:'Demand highly sensitive to interest rates. European demand weakness. Inventory correction cycles.',
   metrics:[{v:'65%',l:'Gross Margin'},{v:'7.8/10',l:'CEO Score'},{v:'$10B',l:'Market Cap'}]},

  {s:'ORCL',n:'Oracle Corp',sec:'Technology',cap:'Large',div:1.2,risk:5,mgmt:7.9,signal:'HOLD',signalType:'hold',
   reason:'OCI cloud acceleration real — GPU compute booked 12 months in advance. Database moat unbreachable in financial systems. Cloud revenue growing 53%. Dividend payer in tech. Hold.',
   confidence:78,
   thesis:"Oracle is the most underappreciated cloud transformation story in enterprise tech. Database business runs 80%+ of critical financial systems. AI training workloads driving massive OCI demand.",
   management:"Safra Catz and Larry Ellison co-run Oracle. Ellison makes decisions with extreme conviction and has been right about the cloud transition. Earnings: 7.9/10.",
   whyfit:'Technology/cloud match. Database moat is essentially unbreachable. Cloud acceleration genuine.',
   risks:"Ellison's age (80+) and succession risk. Complex product portfolio. Higher debt load.",
   metrics:[{v:'1.2%',l:'Yield'},{v:'7.9/10',l:'CEO Score'},{v:'+53%',l:'Cloud Rev Growth'}]},

  {s:'TSM',n:'TSMC',sec:'Technology',cap:'Large',div:1.8,risk:7,mgmt:8.9,signal:'HOLD',signalType:'hold',
   reason:'Manufactures 90%+ of the world\'s most advanced chips. No alternative at leading edge. AI chip demand from NVIDIA, Apple driving record revenue. Taiwan geopolitical risk is the primary watch item — elevated but not imminent.',
   confidence:80,
   thesis:"TSMC manufactures 90%+ of the world's most advanced chips. Every AI chip from NVIDIA, AMD, Apple runs through TSMC. No alternative at the leading edge — manufacturing processes 20+ years ahead of competitors.",
   management:"C.C. Wei is a brilliant operations executive guiding TSMC through extraordinary growth. Maintaining technological leadership requires flawless execution at atomic scale. Earnings: 8.9/10.",
   whyfit:'Technology/semiconductor match. Essential to every advanced tech company on earth. Direct AI beneficiary.',
   risks:'Taiwan geopolitical risk is existential — the biggest geopolitical risk in any stock. US/China tensions. Customer concentration in Apple and NVDA.',
   metrics:[{v:'1.8%',l:'Yield'},{v:'8.9/10',l:'CEO Score'},{v:'90%+',l:'Adv Chip Share'}]},

  // Extended search DB stocks (less full detail)
  {s:'AAPL',n:'Apple Inc',sec:'Technology',cap:'Large',div:0.5,risk:5,mgmt:8.8,signal:'HOLD',signalType:'hold',
   reason:'Services revenue growing 14%. iPhone upgrade cycle muted but installed base loyalty extraordinary. Apple Intelligence features driving upgrade intent for next cycle. Hold.',
   confidence:81,thesis:"Apple owns the most loyal consumer tech ecosystem ever built. Services (App Store, Apple Music, Apple TV+, Apple Pay) growing at 14%+ annually with 75%+ gross margins. Hardware is the gateway, services are the profit engine.",management:"Tim Cook has maintained Apple's culture of secrecy and product excellence. His supply chain expertise is unmatched. The Apple Intelligence AI strategy is measured — not rushing to lead but building on the user trust moat. Earnings: 8.8/10.",whyfit:'Technology sector match. Services margin expansion story. Low risk for a tech stock.',risks:'China manufacturing concentration. App Store antitrust regulation. AI differentiation vs competitors.',metrics:[{v:'0.5%',l:'Yield'},{v:'8.8/10',l:'CEO Score'},{v:'75%',l:'Services Margin'}]},

  {s:'GOOGL',n:'Alphabet',sec:'Technology',cap:'Large',div:0.5,risk:6,mgmt:8.7,signal:'HOLD',signalType:'hold',
   reason:'Search moat intact despite AI competition. YouTube growing 13%+. Google Cloud profitable and growing 28%. Waymo is a free option on autonomous driving. Attractive valuation for growth rate. Hold.',
   confidence:80,thesis:"Alphabet owns the internet's front door (Search), the world's largest video platform (YouTube), a profitable cloud business (Google Cloud), and a portfolio of moonshot bets (Waymo, DeepMind). AI integration across all products is strengthening not weakening the moat.",management:"Sundar Pichai is a steady, thoughtful CEO who has managed the transition to AI era better than critics predicted. The DeepMind integration and Gemini launch demonstrate long-term strategic positioning. Earnings: 8.7/10.",whyfit:'Technology sector match. Most diversified AI business at an attractive valuation relative to peers.',risks:'AI-enabled search disruption risk. Antitrust breakup risk (ongoing DOJ case). Cloud competition from AWS and Azure.',metrics:[{v:'+28%',l:'Cloud Growth'},{v:'8.7/10',l:'CEO Score'},{v:'+13%',l:'YouTube Growth'}]},

  {s:'TSLA',n:'Tesla',sec:'Consumer',cap:'Large',div:0,risk:9,mgmt:7.1,signal:'WATCH',signalType:'watch',
   reason:'FSD progress real but timeline uncertainty high. Robotaxi launch delayed again. Elon Musk\'s political involvement creating brand risk in key markets. EV margin pressure from Chinese competition. Monitoring — consider trimming if brand risk intensifies.',
   confidence:52,thesis:"Tesla leads in EV technology, software, and the Supercharger network. FSD and Robotaxi represent massive optionality if they materialize. Energy storage business growing rapidly.",management:"Elon Musk is the most polarizing CEO in history. His political involvement is creating real brand risk in European and left-leaning US markets. Technical vision remains compelling. Execution on Robotaxi timeline is the key variable. Earnings: 7.1/10.",whyfit:'Consumer sector match. EV leadership + energy storage + autonomous driving optionality.',risks:'Brand risk from CEO political activities. Chinese EV competition. FSD regulatory approval timeline uncertainty.',
   swapSuggestion:{sym:'COST',reason:'If you are concerned about TSLA brand/execution risk, Costco offers consumer sector exposure with 9.4/10 management quality, 93% membership renewal, and an upcoming special dividend.'},
   metrics:[{v:'18%',l:'Auto Margin'},{v:'7.1/10',l:'CEO Score'},{v:'High',l:'Volatility'}]},

  {s:'GS',n:'Goldman Sachs',sec:'Financials',cap:'Large',div:2.4,risk:6,mgmt:8.7,signal:'HOLD',signalType:'hold',
   reason:'M&A volume recovering — investment banking revenue up 24% YoY. Trading desk benefitting from macro volatility. Asset management providing more stable recurring revenue. Rate environment improving for trading. Hold.',
   confidence:76,thesis:"Goldman Sachs is the premier investment bank. In AI era bull markets, every major tech company doing an IPO goes through Goldman. Asset management (GSAM) provides more stable recurring revenues.",management:"David Solomon navigated the failed Marcus consumer banking experiment and refocused Goldman on its core strengths. Goldman's talent culture is a genuine moat. Earnings: 8.7/10.",whyfit:'Financials match. Investment banking cycle upswing benefits Goldman disproportionately.',risks:'Cyclical business — revenues drop 40-60% in recessions. Regulatory capital requirements. Consumer banking losses were costly.',metrics:[{v:'2.4%',l:'Yield'},{v:'8.7/10',l:'CEO Score'},{v:'+24%',l:'IB Revenue'}]},

  {s:'JPM',n:'JPMorgan Chase',sec:'Financials',cap:'Large',div:2.2,risk:5,mgmt:9.4,signal:'HOLD',signalType:'hold',
   reason:'Best-run bank in the world by most metrics. Rate environment improving for net interest income. Jamie Dimon\'s capital allocation is best-in-class. Consistent buybacks and dividend growth. Core financial sector hold.',
   confidence:86,thesis:"JPMorgan is the world's most profitable bank. Consumer banking, investment banking, asset management, and commercial banking operating at scale. Strongest balance sheet among large US banks.",management:"Jamie Dimon is arguably the best bank CEO alive — disciplined, honest about risks, exceptional at capital allocation. His annual letters are required reading for any serious investor. Earnings: 9.4/10.",whyfit:'Financials sector match. Best-run bank. Dividend grower. Core quality hold.',risks:'Economic recession risk. Regulatory capital requirements increasing. Commercial real estate exposure.',metrics:[{v:'2.2%',l:'Yield'},{v:'9.4/10',l:'CEO Score'},{v:'ROE 17%',l:'2025'}]},

  {s:'WMT',n:'Walmart',sec:'Consumer',cap:'Large',div:1.2,risk:2,mgmt:8.7,signal:'HOLD',signalType:'hold',
   reason:'Advertising and marketplace businesses emerging as high-margin growth engines. International growth strong. Defensive in any economic environment. Low risk anchor for conservative portfolios.',
   confidence:85,thesis:"Walmart is evolving from low-cost retailer to a retail ecosystem. Advertising and marketplace revenue growing 30%+ annually at tech-like margins. Walmart+ membership growing. In any recession, consumers trade down to Walmart.",management:"Doug McMillon has transformed Walmart into a technology and data company while maintaining its retail dominance. Advertising business is a brilliant pivot to high-margin revenue. Earnings: 8.7/10.",whyfit:'Consumer/staples match. Low risk. Defensive in recessions. Emerging high-margin business lines.',risks:'E-commerce competitive pressure from Amazon. International execution risk. Labor cost inflation.',metrics:[{v:'1.2%',l:'Yield'},{v:'8.7/10',l:'CEO Score'},{v:'+30%',l:'Ad Revenue Growth'}]},

  {s:'SNOW',n:'Snowflake',sec:'Technology',cap:'Large',div:0,risk:8,mgmt:7.8,signal:'WATCH',signalType:'watch',
   reason:'Revenue growth slowing from hypergrowth pace. Competition from Databricks and Google BigQuery intensifying. New CEO early in tenure — need more data points. Watching but not adding.',
   confidence:57,thesis:"Snowflake is the data cloud platform enabling companies to store, share, and analyze data at scale. The network effect — easy data sharing between companies on the same platform — creates a data marketplace moat.",management:"Sridhar Ramaswamy became CEO in 2024. Background at Google AI directly relevant but too early to have a strong opinion. Earnings: 7.8/10 — early stage.",whyfit:'Technology/cloud SaaS match. Data cloud infrastructure essential for enterprise AI.',risks:'Revenue growth slowing. Competition from Databricks, BigQuery, Redshift. High valuation for decelerating growth.',
   swapSuggestion:{sym:'NOW',reason:'If you want cloud SaaS exposure with more certainty, ServiceNow has deeper switching costs, 9.2/10 CEO quality, and AI expansion that is genuinely accelerating revenue per customer.'},
   metrics:[{v:'+29%',l:'Rev Growth'},{v:'7.8/10',l:'CEO Score'},{v:'67%',l:'Gross Margin'}]},
];

// Extended search DB
const SDB=[...DB,
  {s:'NFLX',n:'Netflix',sec:'Technology',cap:'Large',div:0,risk:7,mgmt:8.2},
  {s:'SPOT',n:'Spotify',sec:'Technology',cap:'Mid',div:0,risk:7,mgmt:7.9},
  {s:'UBER',n:'Uber Technologies',sec:'Consumer',cap:'Large',div:0,risk:7,mgmt:8.2},
  {s:'COIN',n:'Coinbase',sec:'Financials',cap:'Mid',div:0,risk:9,mgmt:7.5},
  {s:'SMCI',n:'Super Micro Computer',sec:'Technology',cap:'Mid',div:0,risk:9,mgmt:6.8},
  {s:'BRKB',n:'Berkshire Hathaway',sec:'Financials',cap:'Large',div:0,risk:3,mgmt:9.8},
  {s:'HD',n:'Home Depot',sec:'Consumer',cap:'Large',div:2.3,risk:4,mgmt:8.5},
  {s:'SBUX',n:'Starbucks',sec:'Consumer',cap:'Large',div:2.8,risk:4,mgmt:7.5},
  {s:'DIS',n:'Walt Disney',sec:'Consumer',cap:'Large',div:0.8,risk:6,mgmt:7.2},
  {s:'PYPL',n:'PayPal Holdings',sec:'Financials',cap:'Large',div:0,risk:6,mgmt:7.3},
  {s:'AMAT',n:'Applied Materials',sec:'Technology',cap:'Large',div:0.9,risk:6,mgmt:8.3},
  {s:'MU',n:'Micron Technology',sec:'Technology',cap:'Large',div:0.5,risk:8,mgmt:7.8},
  {s:'INTC',n:'Intel Corporation',sec:'Technology',cap:'Large',div:0.5,risk:8,mgmt:6.5},
  {s:'LMT',n:'Lockheed Martin',sec:'Industrials',cap:'Large',div:2.9,risk:3,mgmt:8.4},
  {s:'CAT',n:'Caterpillar',sec:'Industrials',cap:'Large',div:1.6,risk:5,mgmt:8.5},
  {s:'DE',n:'Deere & Company',sec:'Industrials',cap:'Large',div:1.4,risk:5,mgmt:8.6},
];

// ════════════════════════════════════════
// NEWS POOL — rotating AI-curated feed
// ════════════════════════════════════════
const NEWS_POOL=[
  {sym:'NVDA',ico:'🤖',title:'Blackwell GPU Demand Exceeds Supply — Third Straight Quarter',src:'The Verge',time:'11:30 AM',imp:'▲ Confirms AI infra thesis',tag:'up',ai:'NVDA supply constraints are a positive signal — demand is outpacing production capacity for the third consecutive quarter. This is unusual and reinforces the bull case. Jensen Huang described it as the most productive backlog in company history. Your 18.2% allocation remains justified. No action needed.'},
  {sym:'MSFT',ico:'☁️',title:'Azure AI Revenue Accelerates to 33% Growth in Q1',src:'CNBC',time:'8:15 AM',imp:'▲ Copilot adoption strong',tag:'up',ai:"Azure's 33% growth beat the 29% consensus estimate. More importantly, Copilot is now generating $10B+ ARR ahead of schedule — Nadella said enterprise seats are expanding faster than any product in Microsoft's history. This is the thesis playing out exactly as expected."},
  {sym:'PLTR',ico:'📊',title:'Karp Buys $2.1M Open Market — Strongest Insider Signal This Year',src:'Reuters',time:'9:42 AM',imp:'▲ Position increased +3.2%',tag:'up',ai:"This is one of the most significant insider signals in our database this year. Non-10b5-1 CEO open-market purchases outperform the market by 8.2% on average over 12 months. Karp knows PLTR's pipeline better than anyone. The purchase was made at $89.40 — current price is $92.30. This is a high-conviction signal."},
  {sym:'JNJ',ico:'💰',title:'J&J Raises Dividend 4.8% — 62nd Consecutive Year',src:'Bloomberg',time:'10:05 AM',imp:'★ DRIP queued Mar 25',tag:'div',ai:"Another year, another dividend increase from Dividend King J&J. At 62 consecutive years, this is one of the longest streaks in S&P 500 history. Your yield-on-cost will compound to approximately 8.4% in 15 years if growth continues at this rate. DRIP is automatically reinvesting your payment into additional shares."},
  {sym:'AMZN',ico:'📦',title:'AWS Margins Hit New High of 38.1% — AI Workloads Driving Mix Shift',src:'WSJ',time:'7:45 AM',imp:'▲ Thesis strengthening',tag:'up',ai:"AWS margins expanding beyond 38% means every AI workload moving to the cloud is more profitable than the existing base. AMZN's advertising business grew 22% alongside this — the two highest-margin businesses Amazon owns are both accelerating simultaneously. The market still under-values this combination."},
  {sym:'MACRO',ico:'🏦',title:'Fed Signals 2 Rate Cuts in H2 2026 — FOMC Minutes',src:'WSJ',time:'2:18 PM',imp:'▲ Growth tech weight raised',tag:'up',ai:"Two confirmed rate cuts in H2 2026 is a tailwind for every growth stock in your portfolio. Lower discount rates make future earnings worth more today — directly benefiting NVDA, MSFT, PLTR, AMZN, and META. We raised your growth tech weight by 5% in response to this signal."},
  {sym:'AVGO',ico:'🔧',title:'Broadcom Custom AI Chips Revenue Hits $4.1B in Q1',src:'FT',time:'3:30 PM',imp:'▲ XPU thesis playing out',tag:'up',ai:"AVGO's custom AI accelerator (XPU) business for Google and Meta is growing faster than consensus expected. At $4.1B in quarterly revenue, XPUs are now the second-largest business segment. Hock Tan's capital allocation track record — the best in semis — means this revenue is being efficiently converted into shareholder value."},
  {sym:'META',ico:'🌐',title:'Llama 4 Achieves State-of-the-Art Benchmarks — Open Source Dominance',src:'TechCrunch',time:'1:15 PM',imp:'▲ Moat deepening',tag:'up',ai:"Llama 4 beating proprietary models on benchmarks is strategically brilliant. By open-sourcing the world's best model, META commoditizes competitors' core products while retaining its data and distribution advantages. Every developer building on Llama deepens Meta's ecosystem moat. 43% operating margins fund this indefinitely."},
  {sym:'NVDA',ico:'💼',title:'Sequoia Increases NVDA Position to $2.1B — New All-Time High',src:'SEC Filing',time:'4:00 PM',imp:'▲ Institutional accumulation',tag:'up',ai:"Sequoia Capital, one of the most respected long-term growth investors, added significantly to their NVDA position. At $2.1B, it's their second-largest holding. 13F filings from top-tier investors corroborate your thesis — smart money is continuing to accumulate on any weakness."},
  {sym:'COST',ico:'🛒',title:'Costco Membership Renewal Rate Hits 93.2% — New All-Time High',src:'Barron\'s',time:'9:00 AM',imp:'▲ Moat strengthening',tag:'up',ai:"93.2% renewal is higher than any point in Costco's history. This is the core moat metric that matters — people who join stay. The special dividend rumor for Q3 2026 is gaining credibility. Ron Vachris is executing the Sinegal playbook with no meaningful deviations. This is exactly what a 9.4/10 management score looks like."},
  {sym:'LLY',ico:'💊',title:'Tirzepatide Beats Ozempic in Head-to-Head Obesity Trial',src:'NEJM',time:'11:00 AM',imp:'▲ GLP-1 market share gaining',tag:'up',ai:"This is the most important clinical result for LLY this year. Tirzepatide showing superior efficacy versus semaglutide in a rigorous trial strengthens Eli Lilly's position in what may be the largest drug market ever created. 1 billion+ people globally qualify for obesity treatment. LLY is winning the best product in the best market."},
  {sym:'V',ico:'💳',title:'Visa Cross-Border Payment Volume Up 16% — Travel Fully Recovered',src:'Reuters',time:'2:45 PM',imp:'▲ Core thesis intact',tag:'up',ai:"Cross-border transactions are the highest-margin segment for Visa, and 16% growth signals complete post-COVID recovery plus underlying secular growth. Visa's toll-road model means every dollar of global GDP growth generates Visa revenue without proportional cost increases. The moat is as deep as ever."},
  {sym:'MACRO',ico:'⚡',title:'AI CapEx from Big Tech Reaches $300B Annual Run Rate',src:'Bloomberg',time:'10:30 AM',imp:'▲ Tailwind for NVDA, AVGO, PLTR',tag:'up',ai:"MSFT, AMZN, GOOGL, and META have committed to $300B+ in combined AI infrastructure spending annually. Every dollar flows through to NVDA (GPUs), AVGO (custom chips), and PLTR (intelligence software). Four of your top six holdings are direct beneficiaries of this spending wave."},
  {sym:'AMD',ico:'🔴',title:'AMD MI300X Gains Share in Inference — Microsoft Azure Adopting',src:'Bloomberg',time:'8:50 AM',imp:'⚡ Watchlist: Monitoring',tag:'neu',ai:"AMD's MI300X winning Microsoft Azure inference workloads is a meaningful development — it's the first major crack in NVIDIA's near-monopoly. This doesn't threaten your NVDA position yet (CUDA switching costs remain extreme), but it's worth monitoring. Lisa Su's execution gives AMD the best chance of any competitor to take meaningful share."},
  {sym:'MACRO',ico:'🌏',title:'Taiwan Strait Tensions Elevated — TSMC Monitoring Daily',src:'Reuters',time:'12:00 PM',imp:'⚠ Watch: NVDA supply chain',tag:'warn',ai:"Elevated Taiwan Strait activity is the primary geopolitical risk in your portfolio. TSMC manufactures chips for NVDA, AMD, and AAPL — supply disruption would impact all three. We're monitoring daily. Currently assessed as elevated but not imminent risk. AVGO's US-fabbed components provide partial hedge."},
  {sym:'NVDA',ico:'🧠',title:'Jensen Huang at Stanford: AI Will Replace Most Knowledge Work by 2030',src:'CNBC',time:'3:00 PM',imp:'▲ Thesis reinforced long-term',tag:'up',ai:"Huang's Stanford speech scored 9.9/10 on our CEO language analysis — the highest score we've given any tech CEO this quarter. Specific predictions, falsifiable timelines, and deep technical credibility. His view on AI replacing knowledge work directly supports NVDA's decade-long demand thesis. No short-term price catalyst but thesis reinforcement."},
  {sym:'PLTR',ico:'🏛️',title:'Palantir Wins $480M US Army AIP Contract Expansion',src:'Defense One',time:'1:00 PM',imp:'▲ Government moat deepening',tag:'up',ai:"A $480M government contract expansion confirms that AIP (AI Platform) is winning mission-critical defense deployments. Government contracts have 20+ year moat characteristics — switching costs are extreme once workflows are embedded. This is the government business thesis playing out. Combined with Karp's insider buy, conviction is high."},
  {sym:'MSFT',ico:'🤖',title:'GitHub Copilot Enterprise Seats Hit 50,000 Paying Companies',src:'Bloomberg',time:'4:15 PM',imp:'▲ Developer moat growing',tag:'up',ai:"50,000 paying enterprise customers for Copilot in under 18 months is exceptional velocity. Developers who build their workflows around Copilot create switching costs for the entire company — not just the individual. This is Microsoft's strategy: embed AI tools so deeply into productivity workflows that switching becomes organizationally impossible."},
  {sym:'JNJ',ico:'⚖️',title:'J&J Talc Litigation Nears Settlement — $8.9B Proposed',src:'WSJ',time:'9:30 AM',imp:'▲ Overhang clearing',tag:'up',ai:"The talc litigation has been the main overhang on JNJ for three years. An $8.9B settlement is at the low end of analyst estimates and removes years of uncertainty. With AAA credit and $22B in free cash flow, JNJ absorbs this and continues compounding. This is a thesis-clearing event."},
  {sym:'MACRO',ico:'📈',title:'S&P 500 Earnings Season: 78% of Companies Beat Estimates',src:'FactSet',time:'5:00 PM',imp:'▲ Broad portfolio tailwind',tag:'up',ai:"A 78% beat rate vs the historical 71% average signals broad corporate health. More importantly, forward guidance upgrades outnumber downgrades 2:1 — companies are more confident about 2026 than analysts modeled. This macro backdrop is supportive of your growth-weighted portfolio."},
];

// ════════════════════════════════════════
// AI AGENTS — definitions & activity log
// ════════════════════════════════════════
const AGENTS_DEF=[
  {id:'news',name:'News Monitor',icon:'📰',status:'active',time:'Updated 30s ago',desc:'Scanning 847 sources for stories tied to your holdings. Filters for relevance and explains market impact in plain English.'},
  {id:'insider',name:'Insider Scanner',icon:'🔍',status:'active',time:'Updated 2m ago',desc:'Monitoring SEC Form 4 filings in real-time. Distinguishes 10b5-1 routine sales from meaningful open-market conviction signals.'},
  {id:'ceo',name:'CEO Score Agent',icon:'🧠',status:'proc',time:'Running now…',desc:'Re-scoring 12 Q1 earnings calls this week. Analyzes specificity, hedging frequency, and forward guidance precision.'},
  {id:'macro',name:'Macro Signal Agent',icon:'🌍',status:'active',time:'Updated 15m ago',desc:'Tracking Fed communications, geopolitical developments, and economic data. Maps every macro event to your specific holdings.'},
  {id:'health',name:'Portfolio Health',icon:'❤️',status:'active',time:'Updated 1h ago',desc:'Monitoring correlation, concentration risk, sector balance, and drawdown exposure. Health score updated daily.'},
  {id:'dca',name:'DCA Scheduler',icon:'📅',status:'active',time:'Next run: Monday',desc:'Automatically queuing your $300/month across holdings. Increases allocation to positions with strongest recent signals.'},
];

const AGENT_LOG=[
  {ico:'📰',sym:'PLTR',body:'Karp interview flagged 3 bullish language patterns. Earnings call confidence score raised 9.1→9.3.',time:'9:42 AM'},
  {ico:'🔍',sym:'AVGO',body:'Hock Tan open-market purchase $4.2M confirmed (non-10b5-1). Signal strength: HIGH.',time:'9:15 AM'},
  {ico:'🌍',sym:'MACRO',body:'Fed minutes confirmed 2 rate cuts H2 2026. Portfolio growth weight raised 5%.',time:'8:30 AM'},
  {ico:'🧠',sym:'MSFT',body:'Nadella Q1 earnings rescored 9.5→9.6. Forward guidance specificity improved significantly.',time:'7:52 AM'},
  {ico:'❤️',sym:'PORTFOLIO',body:'Correlation coefficient 0.72 (elevated). Flagging: consider adding non-tech defensive position.',time:'7:00 AM'},
  {ico:'📅',sym:'DCA',body:'$300 queued: NVDA $54 · MSFT $45 · AMZN $39 · PLTR $36 · JNJ $32 · AVGO $54 · META $40.',time:'6:30 AM'},
  {ico:'📰',sym:'NVDA',body:'Blackwell supply chain data confirmed demand/supply gap widening. Thesis score: 9.8/10.',time:'6:15 AM'},
  {ico:'🔍',sym:'MSFT',body:'Satya Nadella open-market purchase $680K confirmed. Third consecutive quarter of insider buying.',time:'Yesterday'},
  {ico:'🌍',sym:'LLY',body:'GLP-1 market sizing updated: TAM raised to $140B by 2030 following new trial results.',time:'Yesterday'},
];

// ════════════════════════════════════════
// ADAPTIVE QUIZ — 20-question pool
// ════════════════════════════════════════
const QUIZ_POOL=[
  {id:'horizon',q:'When do you plan to use this money?',hint:'Your time horizon is the #1 factor in portfolio design.',opts:[{k:'A',t:'Less than 3 years'},{k:'B',t:'3–7 years'},{k:'C',t:'7–15 years'},{k:'D',t:'15+ years — long-term wealth'}],tag:'horizon'},
  {id:'crash',q:'Portfolio drops 30% tomorrow. You:',hint:'Be honest — this determines how much risk actually suits you.',opts:[{k:'A',t:'Sell everything immediately'},{k:'B',t:'Lose sleep but hold'},{k:'C',t:'Stay calm — long-term'},{k:'D',t:'Buy more — it\'s a discount'}],tag:'risk'},
  {id:'sector',q:'Which sector excites you most?',hint:"We'll overweight your interests while keeping you diversified.",opts:[{k:'A',t:'AI & Technology'},{k:'B',t:'Healthcare & Biotech'},{k:'C',t:'Dividend income — steady compounding'},{k:'D',t:'Let the AI decide'}],tag:'sector'},
  {id:'goal',q:'What matters most to you?',hint:'This shapes your entire portfolio strategy.',opts:[{k:'A',t:'Maximum long-term growth'},{k:'B',t:'Reliable dividend income'},{k:'C',t:'Balanced growth & income'},{k:'D',t:'Capital preservation'}],tag:'goal'},
  {id:'experience',q:'How long have you been investing?',hint:'Helps us calibrate explanations and risk parameters.',opts:[{k:'A',t:'Just starting out'},{k:'B',t:'1–3 years'},{k:'C',t:'3–7 years'},{k:'D',t:'7+ years — experienced'}],tag:'experience'},
  {id:'budget',q:'What is your monthly investment budget?',hint:'Used to size your DCA schedule and position minimums.',opts:[{k:'A',t:'Under $100'},{k:'B',t:'$100–$300'},{k:'C',t:'$300–$1,000'},{k:'D',t:'$1,000+'}],tag:'dca'},
  {id:'concentration',q:'Would you rather hold 5 stocks with conviction or 30 for safety?',hint:'Concentration vs diversification is one of the oldest debates in investing.',opts:[{k:'A',t:'5 stocks — high conviction'},{k:'B',t:'8–12 stocks — focused'},{k:'C',t:'15–25 stocks — balanced'},{k:'D',t:'30+ or just ETFs'}],tag:'concentration'},
  {id:'insider',q:'A CEO buys $2M of their own stock on the open market. This makes you:',hint:'Insider buying is one of the strongest signals we track.',opts:[{k:'A',t:'Much more confident — key signal'},{k:'B',t:'Somewhat more confident'},{k:'C',t:'Neutral — one data point'},{k:'D',t:'Skeptical — could be optics'}],tag:'signals'},
  {id:'rebalance',q:'Your best stock doubles and is now 40% of your portfolio. You:',hint:'How you handle winners reveals a lot about discipline.',opts:[{k:'A',t:'Trim back to original weight'},{k:'B',t:'Let it ride — it\'s a winner'},{k:'C',t:'Sell half and diversify'},{k:'D',t:'Ask the AI to decide'}],tag:'discipline'},
  {id:'macro',q:'The Fed unexpectedly raises rates. Your reaction?',hint:'Macro awareness separates informed investors from reactive ones.',opts:[{k:'A',t:'Panic — bad for growth stocks'},{k:'B',t:'Shift toward dividend stocks'},{k:'C',t:'Stay the course — already positioned'},{k:'D',t:'See which holdings benefit'}],tag:'macro'},
  {id:'leverage',q:'Have you ever used leverage, margin, or options?',hint:'Helps determine whether leveraged ETF strategies are appropriate.',opts:[{k:'A',t:'Never — keep it simple'},{k:'B',t:'Curious but haven\'t tried'},{k:'C',t:'Yes — basic margin'},{k:'D',t:'Yes — actively use options'}],tag:'leverage'},
  {id:'dividend_use',q:'If your holdings paid dividends, you would:',hint:'Your dividend preference shapes sector allocation significantly.',opts:[{k:'A',t:'Reinvest automatically (DRIP)'},{k:'B',t:'Take as income — I need cash flow'},{k:'C',t:'Mix — reinvest some, take some'},{k:'D',t:'Avoid dividends — pure growth only'}],tag:'dividend'},
  {id:'international',q:'International stocks (ASML, TSM, Samsung)?',hint:'International exposure adds diversification but adds currency and geopolitical risk.',opts:[{k:'A',t:'Yes — global diversification matters'},{k:'B',t:'Maybe — only best-in-class'},{k:'C',t:'Prefer US companies'},{k:'D',t:'No — stick to what I know'}],tag:'intl'},
  {id:'esg',q:'Are there industries you want to avoid?',hint:'ESG filters can exclude certain sectors without materially hurting returns.',opts:[{k:'A',t:'Avoid defense and weapons'},{k:'B',t:'Avoid fossil fuels'},{k:'C',t:'Avoid tobacco and gambling'},{k:'D',t:'No filters — maximize returns'}],tag:'esg'},
  {id:'news_habit',q:'How often do you check financial news?',hint:'Informs how much active monitoring vs automated management you want.',opts:[{k:'A',t:'Multiple times daily'},{k:'B',t:'Once a day'},{k:'C',t:'Few times a week'},{k:'D',t:'Rarely — set and forget'}],tag:'engagement'},
  {id:'ai_trust',q:'How much should the AI decide vs you confirming?',hint:'This sets your autonomy level — from fully manual to fully automated.',opts:[{k:'A',t:'AI decides everything — hands off'},{k:'B',t:'AI recommends, I approve major moves'},{k:'C',t:'AI advises, I make all decisions'},{k:'D',t:'I decide — AI is just a resource'}],tag:'autonomy'},
  {id:'sleep_number',q:'At what portfolio drop % would you actually sell?',hint:'The most honest risk question. Your real number is usually lower than you think.',opts:[{k:'A',t:'I\'d sell at -15%'},{k:'B',t:'I could hold through -25%'},{k:'C',t:'I\'d hold through -40%'},{k:'D',t:'I\'d hold through anything if thesis intact'}],tag:'risk'},
  {id:'lump_vs_dca',q:'You receive a $10,000 windfall. You:',hint:'Lump-sum investing beats DCA 70% of the time historically, but DCA reduces regret.',opts:[{k:'A',t:'Invest it all immediately'},{k:'B',t:'Spread over 3 months'},{k:'C',t:'Spread over 6–12 months'},{k:'D',t:'Wait for a dip'}],tag:'dca'},
  {id:'compete',q:'Your friend\'s portfolio is up 40% this year. Yours is up 18%. You feel:',hint:'Benchmarking against others is a major source of investor error.',opts:[{k:'A',t:'Frustrated — need to take more risk'},{k:'B',t:'Curious — what did they buy?'},{k:'C',t:'Unconcerned — I benchmark vs S&P'},{k:'D',t:'Relieved — 18% is strong and sustainable'}],tag:'psychology'},
  {id:'learning',q:'What would make you most confident in a stock pick?',hint:'Understanding what convinces you helps AlphaGen surface the right signals.',opts:[{k:'A',t:'Strong CEO and insider buying'},{k:'B',t:'Dominant market share and moat'},{k:'C',t:'Consistent revenue and earnings growth'},{k:'D',t:'Low valuation relative to peers'}],tag:'signals'},
];
